/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import bd.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author O S C A R
 */
public class gerenteFacturas extends javax.swing.JFrame {

    /**
     * Creates new form gerenteFacturas
     */
    public gerenteFacturas() {
        initComponents();
        conectarBD();
        initTabla();
    }

    private void conectarBD() {
        try {
            //1ºCrear el objeto Connection
            conexion = null;
            conexion = Conexion.mySQL("fruteria4", "root", "");
            if (conexion == null) {
                JOptionPane.showMessageDialog(this, "ERROR, ha sido posible conectar con la BD");
                System.exit(0);
            }
            //2ºCrear el objeto Statement

            sentenciaTicket = conexion.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sentenciaLineaTicket = conexion.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sentenciaProducto = conexion.createStatement();
            sentenciaNombreEmpleado = conexion.createStatement();
            sentenciaCliente = conexion.createStatement();
            sentenciaNumeroTickets = conexion.createStatement();

        } catch (SQLException ex) {
            Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initTabla() {
        modelo = (DefaultTableModel) tabla.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        panelTicket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMetodo = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio/Unidad", "Precio + IVA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TICKETS DE VENTA");

        panelTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Ticket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        panelTicket.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Codigo");
        panelTicket.add(jLabel1);

        txfCodigo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        panelTicket.add(txfCodigo);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Empleado");
        panelTicket.add(jLabel5);

        lblEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpleado.setOpaque(true);
        panelTicket.add(lblEmpleado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Fecha");
        panelTicket.add(jLabel2);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(51, 51, 51));
        lblFecha.setOpaque(true);
        panelTicket.add(lblFecha);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Total");
        panelTicket.add(jLabel9);

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTotal.setOpaque(true);
        panelTicket.add(lblTotal);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Metodo pago");
        panelTicket.add(jLabel11);

        lblMetodo.setBackground(new java.awt.Color(255, 255, 255));
        lblMetodo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMetodo.setOpaque(true);
        panelTicket.add(lblMetodo);

        panelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cliente: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        panelCliente.setLayout(new java.awt.GridLayout(3, 2, 15, 15));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Cliente");
        panelCliente.add(jLabel3);

        lblCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCliente.setOpaque(true);
        panelCliente.add(lblCliente);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tarjeta ");
        panelCliente.add(jLabel4);

        lblTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        lblTarjeta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTarjeta.setOpaque(true);
        panelCliente.add(lblTarjeta);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Telefono");
        panelCliente.add(jLabel6);

        lblTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTelefono.setOpaque(true);
        panelCliente.add(lblTelefono);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(panelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAtras)
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modelo.setRowCount(0);
        int n = Integer.parseInt(txfCodigo.getText());

        lblEmpleado.setText("");
        lblFecha.setText("");
        lblTotal.setText("");
        lblMetodo.setText("");
        lblEmpleado.setText("");

        if (n >= (getNumeroTickets() + 1) || n < 0) {
            JOptionPane.showMessageDialog(this, "Ticket inexistente", "ALERTA", JOptionPane.INFORMATION_MESSAGE);
        } else {

            mostrarDatos();
            mostrarLineaTicket();

            double total = 0;                //Acumulador precio total
            for (int i = 0; i < tabla.getRowCount(); i++) {

                total += (double) tabla.getValueAt(i, 3);//Row de precio

                lblTotal.setText((Math.round(total * 100.0) / 100.0) + " €");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        gerente form = new gerente();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    public void mostrarDatos() {

        cliente c;

        try {
            int codigo = Integer.parseInt(txfCodigo.getText());
            String sql = "SELECT `fecha`, `id_empleado`, `id_cliente` FROM `ticket` WHERE ticket.id = " + codigo;
            resultadoTicket = sentenciaTicket.executeQuery(sql);

            while (resultadoTicket.next()) {

                LocalDate fecha = LocalDate.parse(resultadoTicket.getString(1));
                int codigoEmpleado = resultadoTicket.getInt(2);
                int codigoCliente = resultadoTicket.getInt(3);

                lblEmpleado.setText(getEmpleado(codigoEmpleado));
                lblFecha.setText(fecha + "");
                c = getCliente(codigoCliente);

                if (codigoCliente == 0) { //Pago efectivo -> No hay cliente 
                    lblCliente.setText("");
                    lblTarjeta.setText("");
                    lblTelefono.setText("");
                    lblMetodo.setText("Efectivo");
                } else {  //Pago con tarjeta -> Existe el cliente
                    lblCliente.setText(c.getNombre());
                    lblTarjeta.setText(c.getTarjeta() + "");
                    lblTelefono.setText(c.getTelefono() + "");
                    lblMetodo.setText("Tarjeta");
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(gerenteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public int getNumeroTickets() {
        try {
            String sql = "SELECT COUNT(*) FROM ticket";
            resultadoNumeroTickets = sentenciaNumeroTickets.executeQuery(sql);

            while (resultadoNumeroTickets.next()) {
                return resultadoNumeroTickets.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public void mostrarLineaTicket() {
        lineaProducto linea;
        Producto p;
        try {
            int n = Integer.parseInt(txfCodigo.getText());
            String sql = "SELECT  `idproducto`, `cantidad`, `precio` FROM `lineaticket` WHERE lineaticket.idticket= " + n;
            resultadoLineaTicket = sentenciaLineaTicket.executeQuery(sql);

            Object[] columnas = new Object[4];

            while (resultadoLineaTicket.next()) {
                int idProducto = resultadoLineaTicket.getInt(1);
                int cantidad = resultadoLineaTicket.getInt(2);
                double precio = resultadoLineaTicket.getDouble(3);

                p = getProducto(idProducto);

                columnas[0] = p.getNombre();
                columnas[1] = cantidad;
                columnas[2] = p.getPrecio();
                columnas[3] = precio;

                modelo.addRow(columnas);

            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Producto getProducto(int codigo) {

        try {
            String sql = "SELECT * FROM producto WHERE id = " + codigo;
            resultadoProducto = sentenciaProducto.executeQuery(sql);
            Producto p;
            while (resultadoProducto.next()) {
                int id = resultadoProducto.getInt(1);
                String nombre = resultadoProducto.getString(2);
                double precio = resultadoProducto.getDouble(3);
                int stock = resultadoProducto.getInt(4);
                int iva = resultadoProducto.getInt(5);
                int categoria = resultadoProducto.getInt(6);

                p = new Producto(id, nombre, precio, stock, iva, categoria);
                return p;

            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;

    }

    public String getEmpleado(int id) {

        try {
            String sql = "SELECT nombre FROM empleados WHERE id = " + id;
            resultadoNombreEmpleado = sentenciaNombreEmpleado.executeQuery(sql);

            while (resultadoNombreEmpleado.next()) {
                return resultadoNombreEmpleado.getString(1);

            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public cliente getCliente(int n) {
        cliente c;
        try {
            String sql = "SELECT nombre, telefono FROM clientes WHERE tarjetaCredito = " + n;
            resultadoCliente = sentenciaCliente.executeQuery(sql);

            while (resultadoCliente.next()) {
                String nombre = resultadoCliente.getString(1);
                int telefono = resultadoCliente.getInt(2);
                c = new cliente(n, nombre, telefono);
                return c;
            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerenteFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerenteFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerenteFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerenteFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gerenteFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelTicket;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txfCodigo;
    // End of variables declaration//GEN-END:variables
     private java.sql.Connection conexion;
    private java.sql.Statement sentenciaTicket;
    private java.sql.Statement sentenciaLineaTicket;
    private java.sql.Statement sentenciaProducto;
    private java.sql.Statement sentenciaNombreEmpleado;
    private java.sql.Statement sentenciaCliente;
    private java.sql.Statement sentenciaNumeroTickets;

    private java.sql.ResultSet resultadoTicket;
    private java.sql.ResultSet resultadoProducto;
    private java.sql.ResultSet resultadoLineaTicket;
    private java.sql.ResultSet resultadoNombreEmpleado;
    private java.sql.ResultSet resultadoCliente;
    private java.sql.ResultSet resultadoNumeroTickets;

    private DefaultTableModel modelo;

}
